### ISSUE TITLE
Occasional error in script

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-performance-test#7]
Every once in a while, the `measure.sh` scripts fails in an unrecoverable fashion, failing the whole job.

Here's an example run: https://github.com/camunda/zeebe/actions/runs/5388937809/jobs/9782417213?pr=13143

```
Run ./measure.sh
Waiting for minimal throughput
jq: error (at <stdin>:0): null (null) cannot be parsed as a number
Error: Process completed with exit code 5.
```

Since this is intermittent, even for the same PR, my guess is there's some race condition, and `null` is a possible early value for the call.

This is low severity, mostly just an annoying little thing.

**Comment by megglos** [comment]
ZDP-Triage:
- it failed on all recent benchmarks, we lack the metrics for all benchmarks
- let's fix it asap

**Comment by megglos** [comment]
@oleschoenburg can you support/pair with rodrigo on this, please?
